[project]
name = "personal_ai_assistant"
version = "0.1.0"
description = "personal_ai_assistant using crewAI"
authors = [{ name = "Farheen Fatima", email = "farheenfatima0958@gmail.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.10,<2.0.0",
    "ddgs>=9.15.0",
    "model2vec>=0.9.0",
    "pypdf>=6.17.0",
    "selenium>=4.48.0",
    "streamlit>=1.63.0",
    "streamlit-option-menu>=0.4.0",
]

[project.scripts]
personal_ai_assistant = "personal_ai_assistant.main:run"
run_crew = "personal_ai_assistant.main:run"
train = "personal_ai_assistant.main:train"
replay = "personal_ai_assistant.main:replay"
test = "personal_ai_assistant.main:test"
run_with_trigger = "personal_ai_assistant.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "216ab373-3e84-49e1-a3b8-cfc9ca385d28"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
